name: Django CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [ "3.12" ]  # Use Python 3.10 or 3.11  # Using the latest Python version

    steps:
    - uses: actions/checkout@v2  # Using v2 for stability
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2  # Reverting to v2 for stability
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
