name: Django CI/CD

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
    paths:
      - '**/requirements.txt'  # Trigger the workflow only if requirements.txt changes
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch
    paths:
      - '**/requirements.txt'  # Trigger only when requirements.txt changes

jobs:
  django-test:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu environment
    steps:
      - name: Check out code
        uses: actions/checkout@v2  # Check out the repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version you're using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Set up Django
        run: |
          python manage.py migrate  # Apply migrations if necessary
          python manage.py collectstatic --noinput  # Collect static files if needed

      - name: Run tests
        run: |
          python manage.py test  # Run your tests (make sure they are set up in Django)

      - name: Run the development server (optional for test purposes)
        run: |
          python manage.py runserver 0.0.0.0:8000 &  # Start the Django server in the background (useful for integration tests)

      - name: Verify server is running (optional)
        run: |
          curl --silent --fail http://127.0.0.1:8000  # Ensure server is up (can be useful in integration testing)

